class Config:
    # Model configs...
    MODEL_NAME = '${{API_PYTHON_MODEL_NAME}}'
    MODEL_VERSION = ''
    MODEL_URL = '${{API_PYTHON_MODEL_URL}}'
    MODEL_API_KEY = '${{API_PYTHON_MODEL_API_KEY}}'
    MODEL_MAX_INPUT_TOKENS = '${{API_PYTHON_MODEL_MAX_INPUT_TOKENS}}'
    MODEL_MAX_OUTPUT_TOKENS = '${{API_PYTHON_MODEL_MAX_OUTPUT_TOKENS}}'
    MODEL_INVOCATION_DELAY_IN_SECONDS = '${{API_PYTHON_MODEL_INVOCATION_DELAY_IN_SECONDS}}'

    # Imaging configs...
    IMAGING_URL = '${{API_PYTHON_IMAGING_URL}}'
    IMAGING_API_KEY = ''

    # MongoDB configs...
    MONGODB_CONNECTION_STRING =  '${{API_PYTHON_MONGO_CONNECTION_STRING}}'
    MONGODB_DATABASE_NAME = '${{API_PYTHON_MONGO_DATABASE_NAME}}'

    MAX_THREADS = '${{API_PYTHON_MODEL_MAX_THREADS}}'
    PORT = '${{API_PYTHON_MODEL_PORT}}'

    # Use queue mechanism    
    MQ_VENDOR = '${{API_PYTHON_MQ_VENDOR}}'

    # RabbitMQ Configuration
    RABBITMQ_HOST = ""
    RABBITMQ_PORT = 5672
    RABBITMQ_VHOST = "/"
    RABBITMQ_USER = "guest"
    RABBITMQ_PASSWORD = ""

      # Kafka configs (if used)
    KAFKA_BOOTSTRAP_SERVERS = ""
    KAFKA_GROUP_ID = "cast_ai_group"
    KAFKA_AUTO_OFFSET_RESET = "earliest"